name: open_intent_detection
channels:
  - default
  - conda-forge
dependencies:
  - pip=23.1.2
  - python=3.11.4
  - pip:
      - easydict==1.10
      - json-lines==0.5.0
      - numpy==1.25.1
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - pandas==2.2.3
      - regex==2024.11.6
      - requests==2.32.3
      - scikit-learn==1.6.0
      - scipy==1.11.1
      - setuptools==75.6.0
      - sympy==1.13.3
      - tokenizers==0.19.1
      - torch==2.0.1
      - tqdm==4.67.1
      - transformers==4.42.4
      - peft==0.10.0